install.packages("flexdashboard", dependencies=TRUE)
install.packages("shiny", dependencies=TRUE)
install.packages("dplyr", dependencies=TRUE)
install.packages("stm", dependencies=TRUE)
install.packages("quanteda", dependencies=TRUE)
install.packages("ggplot2", dependencies=TRUE)
install.packages("scales", dependencies=TRUE)
install.packages("devtools", dependencies = TRUE)
devtools::install_github("juliasilge/tidytext")
