install.packages("dplyr", clean = TRUE)
install.packages("ggplot2", clean = TRUE)
install.packages("shiny", clean = TRUE)
install.packages("flexdashboard", clean = TRUE)
install.packages("tidytext", clean = TRUE)
install.packages("quanteda", clean = TRUE)
install.packages("stm", clean = TRUE)
install.packages("scales", clean = TRUE)
